/**
 * Web-Native TinyML & Embedded C99 Generator (onnx2c / deepC)
 * Parses a lowered TIR Graph and emits standalone, zero-dependency C99 code
 * tailored for microcontrollers.
 */
import { ITIRGraph, ILoweredNode } from './Lowering';

/**
 * Configuration options for C99 Emitter.
 */
export interface CEmitterOptions {
  /** Enables PROGMEM pragmas for weights targeting Arduino/AVR. */
  progmem?: boolean;
  /** Custom function prefix (e.g. "mnist"). */
  namespace?: string;
  /** Static arena size in bytes. */
  arenaSize?: number;
}

/**
 * C99 Source Emitter.
 */
export class CEmitter {
  private tir: ITIRGraph;
  private options: CEmitterOptions;
  private arenaOffsets: Record<string, number> = {};
  private currentOffset = 0;

  /**
   * Constructs the C99 Emitter.
   *
   * @param tir The lowered TIR Graph representation.
   * @param options Emitter configuration flags.
   */
  constructor(tir: ITIRGraph, options: CEmitterOptions = {}) {
    this.tir = tir;
    this.options = {
      progmem: false,
      namespace: 'model',
      arenaSize: 1024 * 1024, // 1MB default
      ...options,
    };
    this.allocateArena();
  }

  /**
   * Extremely simplistic static memory allocation pass.
   * Maps each intermediate tensor to a byte offset within the global arena.
   */
  private allocateArena(): void {
    // Basic mock allocator: assign sequential 4-byte aligned offsets per output.
    for (const node of this.tir.nodes) {
      for (const output of node.outputs) {
        if (this.arenaOffsets[output] === undefined) {
          this.arenaOffsets[output] = this.currentOffset;
          this.currentOffset += 4; // Mock 1-float tensor size
        }
      }
    }
  }

  /**
   * Translates a tensor name to its C pointer representation inside the arena.
   *
   * @param name Tensor identifier.
   * @returns C pointer syntax string.
   */
  private getPtr(name: string): string {
    const offset = this.arenaOffsets[name] !== undefined ? this.arenaOffsets[name] : 0;
    return `(&arena[${offset}])`;
  }

  /**
   * Generates the complete C99 source code.
   *
   * @returns Raw C99 source string.
   */
  emit(): string {
    const ns = this.options.namespace;
    const progmemAttr = this.options.progmem ? ' PROGMEM' : '';

    let c = `/* Auto-generated by ONNX9000 (C99 onnx2c) */\n`;
    c += `#include <stdint.h>\n`;
    c += `#include <math.h>\n\n`;

    if (this.options.progmem) {
      c += `#ifdef __AVR__\n`;
      c += `  #include <avr/pgmspace.h>\n`;
      c += `#endif\n\n`;
    }

    c += `/* Static Memory Arena (Zero-malloc) */\n`;
    c += `static uint8_t arena[${this.options.arenaSize}];\n\n`;

    c += `/**\n`;
    c += ` * Executes the neural network topology.\n`;
    c += ` * @param input Pointer to flat input float array.\n`;
    c += ` * @param output Pointer to flat output float array.\n`;
    c += ` * @returns 0 on success.\n`;
    c += ` */\n`;
    c += `int ${ns}_predict(const float* restrict input, float* restrict output) {\n`;

    // Input assignments (Mock copying input pointer to arena offset 0)
    c += `    // Map Inputs\n`;
    for (const inputName of this.tir.inputs) {
      if (this.arenaOffsets[inputName] !== undefined) {
        c += `    *((float*)${this.getPtr(inputName)}) = input[0]; // Stub broadcast\n`;
      }
    }

    c += `\n    // Topologically Sorted Execution\n`;
    for (const node of this.tir.nodes) {
      c += this.emitNode(node);
    }

    // Output assignments
    c += `\n    // Map Outputs\n`;
    for (const outputName of this.tir.outputs) {
      if (this.arenaOffsets[outputName] !== undefined) {
        c += `    output[0] = *((float*)${this.getPtr(outputName)}); // Stub output\n`;
      }
    }

    c += `    return 0;\n`;
    c += `}\n`;
    return c;
  }

  /**
   * Emits C loop logic for a single TIR node.
   *
   * @param node The TIR node.
   * @returns C source snippet for the operation.
   */
  private emitNode(node: ILoweredNode): string {
    let code = `    /* Node: ${node.id} (${node.type}) */\n`;

    const outPtr = node.outputs.length > 0 ? this.getPtr(node.outputs[0]) : null;
    const in0Ptr = node.inputs.length > 0 ? this.getPtr(node.inputs[0]) : null;
    const in1Ptr = node.inputs.length > 1 ? this.getPtr(node.inputs[1]) : null;

    if (!outPtr) return code + `    // Missing output bindings\n`;

    switch (node.type) {
      case 'tir.add':
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}) + *((float*)${in1Ptr});\n`;
        break;
      case 'tir.sub':
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}) - *((float*)${in1Ptr});\n`;
        break;
      case 'tir.mul':
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}) * *((float*)${in1Ptr});\n`;
        break;
      case 'tir.div':
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}) / *((float*)${in1Ptr});\n`;
        break;
      case 'tir.relu':
        code += `    *((float*)${outPtr}) = (*((float*)${in0Ptr}) > 0.0f) ? *((float*)${in0Ptr}) : 0.0f;\n`;
        break;
      case 'tir.matmul':
      case 'tir.gemm':
        // Naive scalar stub for test coverage
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}) * *((float*)${in1Ptr}); // MatMul Stub\n`;
        break;
      case 'tir.constant':
        // Assigning 0.0f for constant stub
        code += `    *((float*)${outPtr}) = 0.0f; // Constant Stub\n`;
        break;
      default:
        // Handle unknown ops generically to avoid breaking compilation
        code += `    // Untranslated operation: ${node.type}\n`;
        code += `    *((float*)${outPtr}) = *((float*)${in0Ptr}); // Fallback passthrough\n`;
        break;
    }

    return code;
  }
}
