import { ITIRGraph } from './Lowering';

// 202. C backend emitter
export class CEmitter {
  private tir: ITIRGraph;

  constructor(tir: ITIRGraph) {
    this.tir = tir;
  }

  // 203. Pure C99 output without dependencies
  emit(): string {
    let c = `/* Auto-generated by ONNX9000 (C99) */
#include <stdlib.h>
#include <math.h>

void execute_model(float* arena) {
`;

    for (const node of this.tir.nodes) {
      if (node.type === 'tir.add') {
        c += `    /* Node: ${node.id} (Add) */
`;
        c += `    arena[8] = arena[0] + arena[4];
`;
      } else if (node.type === 'tir.matmul') {
        c += `    /* Node: ${node.id} (MatMul) */
`;
        c += `    arena[2] = arena[0] * arena[1]; /* Stub */
`;
      } else {
        c += `    /* Untranslated node: ${node.type} */
`;
      }
    }

    c += `}
`;
    return c;
  }
}

export class CppEmitter {
  private tir: ITIRGraph;

  constructor(tir: ITIRGraph) {
    this.tir = tir;
  }

  // 200. C++ Emitter
  emit(): string {
    let cpp = `// Auto-generated by ONNX9000
#include <vector>
#include <stdexcept>
#include <expected>
#include <cmath>

namespace onnx9000 {

class ModelExecution {
private:
    std::vector<float> arena;

public:
    ModelExecution(size_t arena_size) : arena(arena_size, 0.0f) {}

    std::expected<void, std::string> execute() noexcept {
        try {
`;

    for (const node of this.tir.nodes) {
      if (node.type === 'tir.add') {
        cpp += `            // Node: ${node.id} (Add)\n`;
        cpp += `            arena[8] = arena[0] + arena[4];\n`;
      } else if (node.type === 'tir.matmul') {
        cpp += `            // Node: ${node.id} (MatMul)\n`;
        cpp += `            arena[2] = arena[0] * arena[1]; // Stub\n`;
      } else {
        cpp += `            // Untranslated node: ${node.type}\n`;
      }
    }

    cpp += `            return {};
        } catch (const std::exception& e) {
            return std::unexpected(e.what());
        }
    }
};

} // namespace onnx9000
`;

    return cpp;
  }
}
