import { describe, it, expect } from 'vitest';
import { CEmitter } from '../src/compiler/CEmitter';
import { ITIRGraph, ILoweredNode } from '../src/compiler/Lowering';

describe('CEmitter (onnx2c)', () => {
  it('should emit a valid C program with headers and memory arena', () => {
    const graph: ITIRGraph = { inputs: [], outputs: [], nodes: [] };
    const emitter = new CEmitter(graph, { arenaSize: 512, namespace: 'test' });
    const code = emitter.emit();
    expect(code).toContain('/* Auto-generated by ONNX9000 (C99 onnx2c) */');
    expect(code).toContain('#include <stdint.h>');
    expect(code).toContain('static uint8_t arena[512];');
    expect(code).toContain(
      'int test_predict(const float* restrict input, float* restrict output) {',
    );
  });

  it('should emit PROGMEM pragmas if specified', () => {
    const graph: ITIRGraph = { inputs: [], outputs: [], nodes: [] };
    const emitter = new CEmitter(graph, { progmem: true });
    const code = emitter.emit();
    expect(code).toContain('#ifdef __AVR__');
    expect(code).toContain('#include <avr/pgmspace.h>');
  });

  it('should allocate memory offsets correctly for outputs', () => {
    const nodes: ILoweredNode[] = [
      { id: 'n1', type: 'tir.add', inputs: ['in1', 'in2'], outputs: ['out1'], metadata: {} },
      { id: 'n2', type: 'tir.mul', inputs: ['out1', 'in3'], outputs: ['out2'], metadata: {} },
    ];
    const graph: ITIRGraph = { inputs: ['in1', 'in2', 'in3'], outputs: ['out2'], nodes };
    const emitter = new CEmitter(graph);
    const code = emitter.emit();
    expect(code).toContain('(&arena[0])');
    expect(code).toContain('(&arena[4])');
    expect(code).toContain(
      '*((float*)(&arena[0])) = *((float*)(&arena[0])) + *((float*)(&arena[0]))',
    );
  });

  it('should handle all standard tir ops', () => {
    const nodes: ILoweredNode[] = [
      { id: '1', type: 'tir.add', inputs: ['a', 'b'], outputs: ['o1'], metadata: {} },
      { id: '2', type: 'tir.sub', inputs: ['a', 'b'], outputs: ['o2'], metadata: {} },
      { id: '3', type: 'tir.mul', inputs: ['a', 'b'], outputs: ['o3'], metadata: {} },
      { id: '4', type: 'tir.div', inputs: ['a', 'b'], outputs: ['o4'], metadata: {} },
      { id: '5', type: 'tir.relu', inputs: ['a'], outputs: ['o5'], metadata: {} },
      { id: '6', type: 'tir.matmul', inputs: ['a', 'b'], outputs: ['o6'], metadata: {} },
      { id: '7', type: 'tir.gemm', inputs: ['a', 'b'], outputs: ['o7'], metadata: {} },
      { id: '8', type: 'tir.constant', inputs: [], outputs: ['o8'], metadata: {} },
      { id: '9', type: 'tir.unknown', inputs: ['a'], outputs: ['o9'], metadata: {} },
    ];
    const graph: ITIRGraph = { inputs: ['a', 'b'], outputs: ['o1'], nodes };
    const emitter = new CEmitter(graph);
    const code = emitter.emit();
    expect(code).toContain('tir.add');
    expect(code).toContain('tir.sub');
    expect(code).toContain('tir.mul');
    expect(code).toContain('tir.div');
    expect(code).toContain('tir.relu');
    expect(code).toContain('tir.matmul');
    expect(code).toContain('tir.gemm');
    expect(code).toContain('tir.constant');
    expect(code).toContain('tir.unknown');
    expect(code).toContain('Fallback passthrough');
  });

  it('should gracefully handle nodes with missing outputs bindings', () => {
    const nodes: ILoweredNode[] = [
      { id: '1', type: 'tir.add', inputs: ['a', 'b'], outputs: [], metadata: {} },
    ];
    const graph: ITIRGraph = { inputs: ['a', 'b'], outputs: [], nodes };
    const emitter = new CEmitter(graph);
    const code = emitter.emit();
    expect(code).toContain('Missing output bindings');
  });
});
